library(Seurat)
library(ggplot2)
library(cowplot)
library(Matrix)
library(dplyr)
library(enrichR)
library(Seurat)
library(ggplot2)
library(cowplot)
library(Matrix)
library(dplyr)
library(enrichR)
library(pheatmap)

set.seed(1)

saveext = "Naive_primed/"
dir.create(saveext)
dir.create(paste(saveext,"/Markers/",sep=""))
dir.create(paste(saveext,"/DimRed/",sep=""))

cType <-c("4-cell_CS2",
          "8-cell_CS2",
          "Am_CS5",
          "Am_CS5_EmDiscExMes",
          "Am_CS5_ExMes",
          "Am_CS5_ExMes_PGC",
          "Am_CS5_ExMesEmDisc",
          "Am_CS5_ExMesPGC",
          "Am_CS5_PGC",
          "Am_CS5_PGC_ExMes",
          "Am_CS6",
          "Am_CS6_EmDisc",
          "Am_CS6_ExMes",
          "Am_CS7",
          "Am_CS7_EmDisc",
          "Am_CS7_ExMes",
          "Am_CS7_ExMes_Tb",
          "Am_CS7_Stalk",
          "Am_CS7_SYS",
          "cMor_CS3",
          "EmDisc_CS5",
          "EmDisc_CS5_Am",
          "EmDisc_CS5_AmExMes",
          "EmDisc_CS5_Gast",
          "EmDisc_CS5_TbExMes",
          "EmDisc_CS5_VE",
          "EmDisc_CS6",
          "EmDisc_CS6_Am",
          "EmDisc_CS6_ExMes",
          "EmDisc_CS6_Gast",
          "EmDisc_CS6_mix",
          "EmDisc_CS6_SYS",
          "EmDisc_CS6_VE",
          "EmDisc_CS6_VE_ExMes",
          "EmDisc_CS7",
          "EmDisc_CS7_Am",
          "EmDisc_CS7_Gast",
          "EmDisc_CS7_PGC",
          "EmDisc_CS7_VE",
          "EmDisc_Gast_CS6",
          "EmDisc_Gast_CS7",
          "Epi_CS3",
          "ExMes_CS5",
          "ExMes_CS5_Am",
          "ExMes_CS5_Am_EmDisc",
          "ExMes_CS5_ReStroma",
          "ExMes_CS5_Tb",
          "ExMes_CS6",
          "ExMes_CS6_Am",
          "ExMes_CS6_Am_EmDisc",
          "ExMes_CS6_EmDisc",
          "ExMes_CS6_EmDisc_Am_VE",
          "ExMes_CS6_SYS",
          "ExMes_CS6_SYS_Tb",
          "ExMes_CS6_Tb",
          "ExMes_CS6_Tb_QC",
          "ExMes_CS7",
          "ExMes_CS7_Am",
          "ExMes_CS7_EmDisc",
          "ExMes_CS7_F",
          "ExMes_CS7_SYS",
          "ExMes_CS7_Tb",
          "Stalk_CS7",
          "F_CS7_",
          "Gland_CS5",
          "Gland_CS5_Stroma",
          "Gland_CS6",
          "Gland_CS7",
          "Gland_CS7_Mix",
          "Hyp_CS3",
          "ICM_CS3",
          "Myo_CS7",
          "NL_CS7_",
          "Oviduct_CS7",
          "PGC_CS5",
          "PGC_CS6",
          "PGC_CS6_ExMes",
          "PGC_CS7",
          "QC_CS6",
          "ReGland_CS5",
          "ReGland_CS7",
          "ReGland_CS7_Tb",
          "ReStroma_CS5",
          "ReStroma_CS6",
          "ReStroma_CS7",
          "Stalk_CS7",
          "Stalk_CS7_Am",
          "Stalk_CS7_PGC",
          "Stroma_CS5",
          "Stroma_CS5_Tb",
          "Stroma_CS6",
          "Stroma_CS7",
          "Stroma_CS7_Tb",
          "SYS_CS5",
          "SYS_CS6",
          "SYS_CS6_EmDisc",
          "SYS_CS6_ExMes",
          "SYS_CS6_VE",
          "SYS_CS7",
          "SYS_CS7_Am",
          "SYS_CS7_ExMes",
          "SYS_CS7_Tb",
          "Tb_abembryonal_CS5",
          "Tb_abembryonal_CS7",
          "Tb_CS3",
          "Tb_CS5",
          "Tb_CS5_Am",
          "Tb_CS5_ExMe",
          "Tb_CS5_ExMes",
          "Tb_CS5_Gland",
          "Tb_CS5_ReStroma",
          "Tb_CS5_Stroma",
          "Tb_CS6",
          "Tb_CS6_Am",
          "Tb_CS6_ExMes",
          "Tb_CS6_ReStroma",
          "Tb_CS6_Stroma",
          "Tb_CS7",
          "Tb_CS7_ExMes",
          "Tb_CS7_Maternal",
          "Tb_CS7_ReStroma",
          "Tb_CS7_Stroma",
          "VE_CS5",
          "VE_CS5_EmDisc",
          "VE_CS5_Tb",
          "VE_CS6",
          "VE_CS6_EmDisc",
          "VE_CS6_EmDisc_ExMes",
          "VE_CS6_ExMes",
          "VE_CS6_ExMes_SYS",
          "VE_CS7",
          "VE_CS7_EmDisc",
          "Zy_CS1",
          "VE_CS4",
          "Epi_CS4",
          "Tb_CS4",
          "Hyp_CS4",
          "EmDisc_CS6/7",
          "ExMes_CS6/7",
          "PGC_CS6/7",
          "SYS_CS6/7",
          "Tb_CS6/7",
          "EmDiscPS_CS6/7",
          "cylPGC",
          "PGC_CS6/7",
          "PGC_CS5",
          "PGC_E50",
          "Ectoderm",
          "Hemogenic Endothelial Progenitors",
          "Endoderm",
          "Advanced Mesoderm",
          "Primitive Streak",
          "YS Mesoderm",
          "Axial Mesoderm",
          "Erythrocytes",
          "Emergent Mesoderm",
          "Epiblast",
          "Nascent Mesoderm",
          "EmDiscPS_CS5",
          "EmDiscPS_CS6",
          "PGC",
          "Stalk_CS6",
          "Other",
          "pPGC",
          "EVTb_CS5",
          "EVTb_CS6",
          "STb_CS5",
          "STb_CS6",
          "STb_CS7",
          "Blood Progenitors",
          "DE(P)", 
          "Erythroblasts",
          "Hemogenic Endothelium",
          "Non-Neural Ectoderm",
          "Hypoblast",
          "Erythro-Myeloid Progenitors",
          "DE(NP)", 
          "Myeloid Progenitors",
          "YS Endoderm")

BaseCol <- c("#48BF00",
             "#00BF30",
             "#877bd6",
             "#877bd6",
             "#877bd6",
             "#877bd6",
             "#877bd6",
             "#877bd6",
             "#877bd6",
             "#877bd6",
             "#5F54C7",
             "#5F54C7",
             "#5F54C7",
             "#1A0873",
             "#1A0873",
             "#1A0873",
             "#1A0873",
             "#1A0873",
             "#1A0873",
             "#009926",
             "#0c9cf5",
             "#0c9cf5",
             "#0c9cf5",
             "#0c9cf5",
             "#0c9cf5",
             "#0c9cf5",
             "#0767DA",
             "#0767DA",
             "#0767DA",
             "#0767DA",
             "#0767DA",
             "#0767DA",
             "#0767DA",
             "#0767DA",
             "#0233BF",
             "#0233BF",
             "#0233BF",
             "#0233BF",
             "#0233BF",
             "#0767DA",
             "#0233BF",
             "#00BFBF",
             "#e6c800",
             "#e6c800",
             "#e6c800",
             "#e6c800",
             "#e6c800",
             "#c49a00",
             "#c49a00",
             "#c49a00",
             "#c49a00",
             "#c49a00",
             "#c49a00",
             "#c49a00",
             "#c49a00",
             "#c49a00",
             "#967700",
             "#967700",
             "#967700",
             "#967700",
             "#967700",
             "#967700",
             "#603813",
             "#000000",
             "#C0C0C0",
             "#C0C0C0",
             "#C0C0C0",
             "#C0C0C0",
             "#C0C0C0",
             "#E6B500",
             "#00E6E6",
             "#E6E6FA",
             "#000000",
             "#000000",
             "#E6E600",
             "#BFBF04",
             "#BFBF04",
             "#999903",
             "#000000",
             "#A9A9A9",
             "#A9A9A9",
             "#A9A9A9",
             "#C0C0C0",
             "#C0C0C0",
             "#C0C0C0",
             "#603813",
             "#603813",
             "#603813",
             "#C0C0C0",
             "#C0C0C0",
             "#C0C0C0",
             "#C0C0C0",
             "#C0C0C0",
             "#E68600",
             "#d17600",
             "#d17600",
             "#d17600",
             "#d17600",
             "#BF7104",
             "#BF7104",
             "#BF7104",
             "#BF7104",
             "#921FE6",
             "#7108a6",
             "#BF0489",
             "#921FE6",
             "#921FE6",
             "#921FE6",
             "#921FE6",
             "#921FE6",
             "#921FE6",
             "#921FE6",
             "#8017c2",
             "#8017c2",
             "#8017c2",
             "#8017c2",
             "#8017c2",
             "#7108a6",
             "#7108a6",
             "#7108a6",
             "#7108a6",
             "#7108a6",
             "#F04C04",
             "#F04C04",
             "#F04C04",
             "#D74404",
             "#D74404",
             "#D74404",
             "#D74404",
             "#D74404",
             "#BF3C04",
             "#BF3C04",
             "#56E600",
             "#F04C04",
             "#00BFBF",
             "#BF0489",
             "#E6B500",
             "#0767DA",
             "#c49a00",
             "#BFBF04",
             "#d17600",
             "#8017c2",
             "#0767DA",
             "#999903",
             "#BFBF04",
             "#E6E600",
             "#999903",
             "#1A0873",
             "#4d4d4d",
             "#BF3C04",
             "#662506",
             "#ec7014",
             "#BF7104",
             "#BF7104",
             "#4d4d4d",
             "#993404",
             "#0233BF",
             "#cc4c02",
             "#0c9cf5",
             "#0767DA",
             "#E6E600",
             "#754C24",
             "lightgrey",
             "#E6E600",
             "#dcd0ff",
             "#734f96",
             "#7A4988",
             "#630436",
             "#601A35",
             "#f80000",
             "#BF3C04",
             "#1c0000",
             "#7c0000",
             "#1A0873",
             "#E6B500",
             "#ba0000",
             "#D74404",
             "#3e0000",
             "#BF7104")

#mammal.anchors <- FindIntegrationAnchors(object.list = list(marmoset_dataInVivo, PSC), dims = 1:20, anchor.features = 4000, k.filter = 30)
#mammal.combined <- IntegrateData(anchorset = mammal.anchors, dims = 1:20)
#DefaultAssay(mammal.combined) <- "integrated"
#mammal.combined <- ScaleData(mammal.combined, verbose = FALSE)
#mammal.combined <- RunPCA(mammal.combined, npcs = 20, verbose = FALSE)
#mammal.combined <- RunUMAP(mammal.combined, reduction = "pca", dims = 1:20)
#mammal.combined <- RunTSNE(mammal.combined, reduction = "pca", dims = 1:20)
#mammal.combined <- FindNeighbors(mammal.combined, reduction = "pca", dims = 1:20)
##mammal.combined <- FindClusters(mammal.combined, resolution = 0.5)

mammal.combined <- readRDS("../Data/Primed_Niave.rds")

#Plot the first 2 PCs
DimPlot(mammal.combined, reduction = "pca",  pt.size = 2,  label.size = 2,  split.by = "Dataset", label = TRUE, repel = TRUE) #+ NoLegend()
ggsave(filename=paste(saveext,"/DimRed/PCA_Type",".pdf",sep=""),width = 26, height = 8)

#For cross-species comparisons use the corrected (integrated) slot for comparisons
E1 <- GetAssayData(mammal.combined,assay="integrated")

ind1 <- which(mammal.combined$Stage=="CS5" | mammal.combined$Stage=="CS6" | mammal.combined$Stage=="CS7" | mammal.combined$Stage=="Pre")
ind2 <- which(mammal.combined$Stage=="Invitro")
ind3 <- which(mammal.combined$Dataset=="hPSC")

#Get the correlations and write to file (these will be used later for 3D mapping etc)
C1 <- cor( as.matrix(E1[,ind1]),as.matrix(E1[,ind2]),method="pearson")
C2 <- cor( as.matrix(E1[,ind1]),as.matrix(E1[,ind3]),method="pearson")
write.csv(as.data.frame(C1) , file=paste(saveext,"/Marm_InVit_Int.csv",sep=""))
write.csv(as.data.frame(C2) , file=paste(saveext,"/Marm_PSC_Int.csv",sep=""))
write.csv(as.data.frame(Idents(mammal.combined)[ind1]) , file=paste(saveext,"/Marm_Idents.csv",sep=""))
write.csv(as.data.frame(Idents(mammal.combined)[ind2]) , file=paste(saveext,"/InVit_Idents.csv",sep=""))
write.csv(as.data.frame(Idents(mammal.combined)[ind3]) , file=paste(saveext,"/PSC_Idents.csv",sep=""))
write.csv(as.data.frame(mammal.combined$LOC[ind1]) , file=paste(saveext,"/Marm_LOCS.csv",sep=""))

#Now subcluster the data (try different resolutions)
mammal.combined <- FindClusters(mammal.combined, resolution = 0.8)
mammal.combined$Cl8 <- Idents(mammal.combined)
DimPlot(mammal.combined, pt.size = 4, reduction = "pca", split.by = "Dataset", label = TRUE, repel = TRUE)
ggsave(filename=paste(saveext,"/DimRed/PCA_Cl8.pdf",sep=""),width = 32, height = 8)

mammal.combined <- FindClusters(mammal.combined, resolution = 0.5)
mammal.combined$Cl5 <- Idents(mammal.combined)
DimPlot(mammal.combined, pt.size = 4, reduction = "pca", split.by = "Dataset", label = TRUE, repel = TRUE)
ggsave(filename=paste(saveext,"/DimRed/PCA_Cl5.pdf",sep=""),width = 32, height = 8)

#Write out clusters 
write.csv(as.data.frame( mammal.combined$Cl5[ind1]) , file=paste(saveext,"/Marm_Cl5.csv",sep=""))
write.csv(as.data.frame( mammal.combined$Cl5[ind2]) , file=paste(saveext,"/InVit_Cl5.csv",sep=""))
write.csv(as.data.frame( mammal.combined$Cl5[ind3]) , file=paste(saveext,"/PSC_Cl5.csv",sep=""))

#Could do for the RNA-slot ... but better to use integrated for cross-species/cross-platform comparisons
#E2 <- GetAssayData(mammal.combined,assay="RNA")
#C3 <- cor( as.matrix(E2[,ind1]),as.matrix(E2[,ind2]),method="pearson")
#C4 <- cor( as.matrix(E2[,ind1]),as.matrix(E2[,ind3]),method="pearson")
#write.csv(as.data.frame(C3) , file=paste(saveext,"/Marm_InVit_RNA.csv",sep=""))
#write.csv(as.data.frame(C3) , file=paste(saveext,"/Marm_PSC_RNA.csv",sep=""))